Repository dev-cucei-itrans/siiau-api-client, pull requests merged in 2023-10, with the labels that each got.

#5 Crear request para validar credenciales
  src/Requests/ValidarCredencialesRequest.php
Labels: enhancement

#7 Creación de resources
  .php-cs-fixer.php
  src/Resources/AlumnoResource.php
  src/Resources/UsuarioResource.php
  src/SiiauConnector.php
Labels: enhancement

#9 Implementar facade del conector
  .gitignore
  .php-cs-fixer.php
  composer.json
  config/config.php
  phpunit.xml.dist
  src/Facades/Siiau.php
  src/Requests/GetAlumnoRequest.php
  src/Resources/AlumnoResource.php
  src/SiiauApiClientServiceProvider.php
  tests/Pest.php
  tests/TestCase.php
Labels: enhancement

#12 fix: no reconoce service provider
  tests/Feature/ExampleTest.php
  tests/TestCase.php
Labels: bug

#13 feat: mejorado lanzamiento de errores
  composer.json
  src/Exceptions/ClientException.php
  src/Exceptions/InternalServerErrorException.php
  src/Exceptions/InvalidCredentialsException.php
  src/Exceptions/NotFoundException.php
  src/Exceptions/ServerException.php
  src/Exceptions/SiiauRequestException.php
  src/Handlers/RetryFatalAndServerErrors.php
  src/Objects/Token.php
  src/Requests/LoginRequest.php
  src/SiiauApiClientServiceProvider.php
  src/SiiauAuthenticator.php
  src/SiiauConnector.php
Labels: enhancement

#18 Carreras de alumno duplicadas
  src/Requests/CarrerasAlumnoRequest.php
Labels: bug

#21 Update README.md
  README.md
Labels: documentation

#23 Siiau user provider
  README.md
  src/Concerns/HasCodigoSiiau.php
  src/Contracts/SiiauAuthenticable.php
  src/Extensions/SiiauUserProvider.php
  src/Requests/ValidarCredencialesRequest.php
  src/Resources/UsuarioResource.php
  src/SiiauApiClientServiceProvider.php
  src/SiiauConnector.php
Labels: enhancement
